---
scale: 0.8
panel_width: 100
panel_height: 175
marker_size: 12
body_parts:
  head:
  - 35
  - 3
  neck:
  - 36
  - 20
  chest:
  - 36
  - 40
  abdomen:
  - 35
  - 66
  back:
  - 0
  - 131
  leftArm:
  - 59
  - 48
  rightArm:
  - 11
  - 45
  leftHand:
  - 65
  - 84
  rightHand:
  - 8
  - 84
  leftLeg:
  - 48
  - 98
  rightLeg:
  - 24
  - 99
  leftFoot:
  - 51
  - 146
  rightFoot:
  - 19
  - 146
  leftEye:
  - 65
  - -1
  rightEye:
  - 4
  - 1
  nerves:
  - 69
  - 131
name_display:
  show: false
  font_size: 8
  font_family: ''
  font_weight: bold
  max_length: 30
  mode: noun
hp_bar:
  height: 12
  width: 80
  show_text: false
  show_percentage: false
  text_style: overlay
  font_size: 8
  ranges:
    low:
      min: 0
      max: 33
    mid:
      min: 34
      max: 66
    high:
      min: 67
      max: 100
  show_hp_prefix: false
  show_numbers: true
  show: true
  show_bar: true
status:
  show: true
  font_size: 8
